const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { openDatabase } = require('../db/database');
const { createStore } = require('../db/stacks');
function setup(t,filename=':memory:') {
  const db = openDatabase(filename); t.after(()=>db.close());
  for (const [i,code] of [...'ABCXYZQ'].entries()) db.prepare('INSERT INTO albums VALUES(?,?,?,?,?,?)').run(i+1,code,'Artist',code,code==='Q'?'4B':i%2?'17A':'17D',code==='Q'?4:17);
  const store=createStore(db);
  const act=(type,data={})=>store.action(store.snapshot().revision,type,data);
  const scan=(codes,label='14C')=>{
    act('createSource',{label}); const id=store.snapshot().sources[0].id;
    for(const barcode of codes) act('scan',{id,barcode});
    act('finishScan',{id}); return id;
  };
  const drain=()=>{while(store.snapshot().session.status==='active') act('next',{id:store.snapshot().session.id});};
  const order=()=>db.prepare('SELECT a.barcode FROM column_items c JOIN albums a ON a.id=c.album_id WHERE column_id=17 ORDER BY position DESC').all().map(x=>x.barcode).join('');
  return {db,store,act,scan,drain,order};
}
test('scan order, source reversal, persistent second source, exact undo',t=>{
  const {db,store,act,scan,drain,order}=setup(t);
  const first=scan('CBA');
  assert.deepEqual(db.prepare('SELECT album_id FROM source_items ORDER BY position').all().map(x=>x.album_id),[3,2,1]);
  act('startSource',{id:first}); drain(); assert.equal(order(),'ABC');
  const second=scan('XYZ','15A'); act('startSource',{id:second});
  const sid=store.snapshot().session.id;
  act('next',{id:sid}); act('next',{id:sid});
  act('undo',{id:sid}); assert.equal(order(),'XABC'); assert.equal(store.snapshot().session.next.barcode,'Y');
  drain(); assert.equal(order(),'ZYXABC'); // X, Y, Z are each placed ON TOP.
  const completed=store.snapshot();
  assert.throws(()=>act('undo',{id:sid}),/complete/);
  assert.deepEqual(store.snapshot(),completed);
  act('startColumn',{id:17}); const final=store.snapshot().session.id;
  const seen=[];
  while(store.snapshot().session.status==='active') { seen.push(store.snapshot().session.next.barcode); act('next',{id:final}); }
  assert.equal(seen.join(''),'ZYXABC'); assert.equal(order(),'');
  assert.equal(store.snapshot().session.cursor,6);
  const finished=store.snapshot();
  assert.throws(()=>act('undo',{id:final}),/complete/);
  assert.deepEqual(store.snapshot(),finished); assert.equal(order(),'');
  assert.throws(()=>act('startSource',{id:first}),/finished, unsorted/);
  assert.throws(()=>act('startColumn',{id:17}),/empty/);
  assert.throws(()=>act('undo',{id:sid}),/most recent/);
});
test('duplicate, empty, invalid and stale requests leave state unchanged',t=>{
  const {store,act}=setup(t);
  assert.throws(()=>act('createSource',{label:'33A'}),/shelf label/);
  act('createSource',{label:'1A'}); const id=store.snapshot().sources[0].id;
  assert.throws(()=>act('finishScan',{id}),/at least/);
  act('scan',{id,barcode:'A'}); const before=store.snapshot();
  assert.throws(()=>act('scan',{id,barcode:'A'}),/DUPLICATE/);
  assert.throws(()=>act('scan',{id,barcode:'   '}),/empty/);
  assert.throws(()=>store.action(before.revision-1,'scan',{id,barcode:'B'}),/State changed/);
  assert.deepEqual(store.snapshot(),before);
});
test('close and reopen resumes scanning, source sorting and final sorting',t=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shelf-test-')); t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  const file=path.join(dir,'test.db');
  let db=openDatabase(file);
  for(const [i,c] of [...'ABC'].entries()) db.prepare('INSERT INTO albums VALUES(?,?,?,?,?,?)').run(i+1,c,'Artist',c,'17D',17);
  let store=createStore(db);
  const act=(type,data)=>store.action(store.snapshot().revision,type,data);
  const reopen=()=>{db.close(); db=openDatabase(file); store=createStore(db);};
  act('createSource',{label:'14C'}); act('scan',{id:1,barcode:'A'}); reopen();
  assert.equal(store.snapshot().sources[0].count,1);
  act('scan',{id:1,barcode:'B'}); act('scan',{id:1,barcode:'C'}); act('finishScan',{id:1});
  act('startSource',{id:1}); act('next',{id:1}); reopen();
  assert.equal(store.snapshot().session.next.barcode,'B');
  act('undo',{id:1}); assert.equal(store.snapshot().session.next.barcode,'A');
  for(let i=0;i<3;i++) act('next',{id:1});
  act('startColumn',{id:17}); act('next',{id:2}); reopen();
  assert.equal(store.snapshot().session.next.barcode,'B');
  act('undo',{id:2}); assert.equal(store.snapshot().session.next.barcode,'C'); db.close();
});
test('one sorting session at a time; mixed destinations; transactional rollback on failure',t=>{
  const {db,store,act,scan,order}=setup(t);
  const id=scan('AQB'); act('startSource',{id}); act('next',{id:1});
  assert.throws(()=>act('startColumn',{id:17}),/Resume/);
  act('next',{id:1}); assert.equal(order(),'A');
  act('undo',{id:1}); assert.equal(db.prepare('SELECT count(*) n FROM column_items WHERE column_id=4').get().n,0);
  // Force a database write failure after the column INSERT; the whole move must roll back.
  db.exec("CREATE TRIGGER fail_progress BEFORE UPDATE ON sessions BEGIN SELECT RAISE(ABORT,'test failure'); END;");
  const before=store.snapshot();
  assert.throws(()=>act('next',{id:1}),/test failure/);
  assert.deepEqual(store.snapshot(),before);
  assert.equal(db.prepare('SELECT count(*) n FROM column_items WHERE column_id=4').get().n,0);
});

test('ten-album preview follows physical order through moves, undo and resume in both stages',t=>{
  const db=openDatabase(':memory:');t.after(()=>db.close());
  const store=createStore(db);
  const act=(type,data)=>store.action(store.snapshot().revision,type,data);
  const codes=Array.from({length:12},(_,i)=>`CD${i+1}`);
  codes.forEach((code,i)=>db.prepare('INSERT INTO albums VALUES(?,?,?,?,?,?)').run(i+1,code,'Artist',code,i%2?'17A':'17D',17));
  act('createSource',{label:'14C'});
  codes.forEach(barcode=>act('scan',{id:1,barcode}));
  act('finishScan',{id:1});act('startSource',{id:1});
  const preview=()=>store.snapshot().session.upcoming.map(a=>a.barcode);
  assert.deepEqual(preview(),codes.slice(0,10));
  act('next',{id:1});assert.deepEqual(preview(),codes.slice(1,11));
  assert.deepEqual(createStore(db).snapshot().session.upcoming.map(a=>a.barcode),codes.slice(1,11));
  act('undo',{id:1});assert.deepEqual(preview(),codes.slice(0,10));
  for(let i=0;i<12;i++)act('next',{id:1});
  assert.deepEqual(preview(),[]);
  act('startColumn',{id:17});
  const reversed=[...codes].reverse();
  assert.deepEqual(preview(),reversed.slice(0,10));
  act('next',{id:2});assert.deepEqual(preview(),reversed.slice(1,11));
  act('undo',{id:2});assert.deepEqual(preview(),reversed.slice(0,10));
  for(let i=0;i<10;i++)act('next',{id:2});
  assert.deepEqual(preview(),['CD2','CD1']);
  assert.equal(store.snapshot().session.upcoming[0].position,10);
  act('next',{id:2});act('next',{id:2});assert.deepEqual(preview(),[]);
});

test('group boundaries survive restart; Undo reverses mixed-column groups exactly; completion is final',t=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shelf-groups-'));
  t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  const file=path.join(dir,'groups.db');
  let db=openDatabase(file), store=createStore(db);
  t.after(()=>db.close());
  const act=(type,data)=>store.action(store.snapshot().revision,type,data);
  for(let i=1;i<=33;i++) db.prepare('INSERT INTO albums VALUES(?,?,?,?,?,?)').run(i,`CD${i}`,'Artist',`Album ${i}`,i===2?'4B':'17D',i===2?4:17);
  const scan=(from,to,label)=>{
    act('createSource',{label});const id=store.snapshot().sources[0].id;
    for(let i=from;i<=to;i++)act('scan',{id,barcode:`CD${i}`});
    act('finishScan',{id});act('startSource',{id});
    return store.snapshot().session.id;
  };
  const columns=()=>db.prepare('SELECT * FROM column_items ORDER BY column_id,position DESC').all();
  const first=scan(1,3,'1A');act('nextGroup',{id:first});const original=columns();
  assert.equal(store.snapshot().session.cursor,3);
  const second=scan(4,33,'1B');act('nextGroup',{id:second});
  assert.equal(store.snapshot().session.cursor,10);
  assert.deepEqual(store.snapshot().session.undoItems.map(x=>x.barcode),Array.from({length:10},(_,i)=>`CD${13-i}`));
  db.close();db=openDatabase(file);store=createStore(db);
  act('undo',{id:second});assert.deepEqual(columns(),original);assert.equal(store.snapshot().session.cursor,0);
  act('nextGroup',{id:second});act('nextGroup',{id:second});
  act('undo',{id:second});assert.equal(store.snapshot().session.cursor,10);
  act('nextGroup',{id:second});act('nextGroup',{id:second});
  const sourceDone=store.snapshot();assert.throws(()=>act('undo',{id:second}),/complete/);assert.deepEqual(store.snapshot(),sourceDone);
  const beforeFinal=columns();act('startColumn',{id:17});const final=store.snapshot().session.id;
  const originalOrder=beforeFinal.filter(x=>x.column_id===17).map(x=>x.album_id);
  assert.deepEqual(store.snapshot().session.upcoming.map(x=>x.album_id),originalOrder.slice(0,10));
  act('nextGroup',{id:final});
  db.close();db=openDatabase(file);store=createStore(db);
  act('undo',{id:final});assert.deepEqual(columns(),beforeFinal);
  while(store.snapshot().session.status==='active')act('nextGroup',{id:final});
  assert.equal(store.snapshot().session.cursor,32);
  assert.equal(columns().filter(x=>x.column_id===17).length,0);
  db.close();db=openDatabase(file);store=createStore(db);
  const finalDone=store.snapshot();assert.throws(()=>act('undo',{id:final}),/complete/);assert.deepEqual(store.snapshot(),finalDone);
  assert.deepEqual(store.snapshot().session.undoItems,[]);
});

test('failure halfway through group advance or Undo rolls back every item and group boundary',t=>{
  const db=openDatabase(':memory:');t.after(()=>db.close());const store=createStore(db);
  const act=(type,data)=>store.action(store.snapshot().revision,type,data);
  for(let i=1;i<=12;i++)db.prepare('INSERT INTO albums VALUES(?,?,?,?,?,?)').run(i,`CD${i}`,'Artist','Album',i%2?'17D':'4B',i%2?17:4);
  act('createSource',{label:'14C'});
  for(let i=1;i<=12;i++)act('scan',{id:1,barcode:`CD${i}`});
  act('finishScan',{id:1});act('startSource',{id:1});
  db.exec("CREATE TRIGGER fail_group BEFORE UPDATE ON sessions WHEN NEW.cursor=5 BEGIN SELECT RAISE(ABORT,'group failure'); END;");
  const before=store.snapshot();
  assert.throws(()=>act('nextGroup',{id:1}),/group failure/);
  assert.deepEqual(store.snapshot(),before);
  assert.equal(db.prepare('SELECT count(*) n FROM session_actions').get().n,0);
  assert.equal(db.prepare('SELECT count(*) n FROM column_items').get().n,0);
  db.exec('DROP TRIGGER fail_group');act('nextGroup',{id:1});
  assert.equal(store.snapshot().columns.length,2);
  const moved=store.snapshot(), items=db.prepare('SELECT * FROM column_items ORDER BY position').all();
  db.exec("CREATE TRIGGER fail_undo BEFORE UPDATE ON sessions WHEN NEW.cursor=5 BEGIN SELECT RAISE(ABORT,'undo failure'); END;");
  assert.throws(()=>act('undo',{id:1}),/undo failure/);
  assert.deepEqual(store.snapshot(),moved);assert.deepEqual(db.prepare('SELECT * FROM column_items ORDER BY position').all(),items);
  db.exec('DROP TRIGGER fail_undo');act('undo',{id:1});
  assert.equal(store.snapshot().session.cursor,0);assert.deepEqual(store.snapshot().columns,[]);
});

test('albums can be sorted repeatedly; only unfinished physical membership blocks another scan',t=>{
  const {db,store,act,scan,drain}=setup(t);
  const first=scan('AB');act('startSource',{id:first});drain();
  act('createSource',{label:'2A'});const second=store.snapshot().sources[0].id;
  assert.throws(()=>act('scan',{id:second,barcode:'A'}),/unfinished stack/);
  act('startColumn',{id:17});const columnSession=store.snapshot().session.id;
  act('next',{id:columnSession});
  // A CD already put on a final shelf is still undoable until this session finishes.
  assert.throws(()=>act('scan',{id:second,barcode:'B'}),/unfinished stack/);
  drain();
  act('scan',{id:second,barcode:'A'});act('scan',{id:second,barcode:'B'});
  assert.throws(()=>act('scan',{id:second,barcode:'A'}),/DUPLICATE/);
  act('finishScan',{id:second});act('startSource',{id:second});drain();
  act('startColumn',{id:17});drain();
  assert.equal(store.snapshot().columns.length,0);
  assert.equal(db.prepare('SELECT count(*) n FROM albums').get().n,7);
  assert.equal(db.prepare('SELECT count(*) n FROM source_items WHERE album_id=1').get().n,2);
  assert.equal(db.prepare("SELECT name FROM sqlite_master WHERE name='finished_albums'").get(),undefined);
});

test('unknown scans retain their exact position across restart, set-aside moves and group Undo',t=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shelf-unknown-'));
  t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  const filename=path.join(dir,'test.db');let db=openDatabase(filename),store=createStore(db);
  t.after(()=>db.close());const act=(type,data)=>store.action(store.snapshot().revision,type,data);
  for(let i=1;i<=9;i++)db.prepare('INSERT INTO albums VALUES(?,?,?,?,?,?)').run(i,`CD${i}`,'Artist','Album','17D',17);
  const codes=['CD1','UNKNOWN-1','CD2','UNKNOWN-2','CD3','CD4','CD5','CD6','CD7','CD8','CD9'];
  act('createSource',{label:'14C'});
  codes.forEach(barcode=>act('scan',{id:1,barcode}));
  assert.equal(store.snapshot().sources[0].count,11);
  assert.throws(()=>act('scan',{id:1,barcode:'UNKNOWN-1'}),/DUPLICATE/);
  assert.equal(db.prepare('SELECT count(*) n FROM albums').get().n,9);
  db.close();db=openDatabase(filename);store=createStore(db);
  act('finishScan',{id:1});act('startSource',{id:1});
  assert.deepEqual(store.snapshot().session.upcoming.map(x=>x.barcode),codes.slice(0,10));
  assert.equal(store.snapshot().session.upcoming[1].album_id,null);
  act('nextGroup',{id:1});assert.equal(store.snapshot().session.cursor,10);
  assert.equal(store.snapshot().columns[0].count,8);
  assert.deepEqual(store.snapshot().session.undoItems.map(x=>x.barcode),codes.slice(0,10).reverse());
  db.close();db=openDatabase(filename);store=createStore(db);
  act('undo',{id:1});assert.deepEqual(store.snapshot().columns,[]);
  assert.deepEqual(store.snapshot().session.upcoming.map(x=>x.barcode),codes.slice(0,10));
  act('nextGroup',{id:1});act('nextGroup',{id:1});
  act('startColumn',{id:17});
  assert.deepEqual(store.snapshot().session.upcoming.map(x=>x.barcode),Array.from({length:9},(_,i)=>`CD${9-i}`));
  act('nextGroup',{id:2});assert.deepEqual(store.snapshot().columns,[]);
  act('createSource',{label:'14D'});act('scan',{id:2,barcode:'UNKNOWN-1'});
  assert.equal(store.snapshot().sources[0].last.barcode,'UNKNOWN-1');
  assert.equal(store.snapshot().sources[0].last.album_id,null);
  act('finishScan',{id:2});act('startSource',{id:2});
  act('nextGroup',{id:3});assert.equal(store.snapshot().session.status,'done');
  assert.deepEqual(store.snapshot().columns,[]);
});
